# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ MedTrainer]

name: Learning

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new app
    actions:
      - scripts:
        - mkdir ${CREATE_DIRECTORY}


# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: Setup
    actions:
      - recipe: setup-irene
      - recipe: setup-spa
      - recipe: setup-rustici-engine
      - recipe: setup-monolith
      - recipe: setup-course-assignments
      - recipe: setup-provider-profile
