services:
  course-assignments:
    build:
      context: irene/reverse-proxy
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ${COURSE_ASSIGNMENTS_CODE_PATH_HOST}:/var/www/course-assignments
      - ${PWD}/irene/reverse-proxy/sites/course-assignments.conf:/etc/nginx/sites-enabled/course-assignments.conf
    ports:
      - "82"
      - "8082:8082"
    networks: [backend]
    depends_on:
      - gateway
      - course-assignments-api
      - course-assignments-worker

  course-assignments-worker:
    build:
      target: development
      dockerfile: irene/course-assignments-api/Dockerfile
      args:
        APP_DIR: ${CONTAINER_APP_PATH}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_SESSION: PHPSTORM_COURSE_ASSIGNMENTS
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
      XDEBUG_CONFIG: "idekey=PHPSTORM_COURSE_ASSIGNMENTS_BACKEND"
      XDEBUG_MODE: debug
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@medtrainer_db/${MONOLITH_DATABASE}?serverVersion=8&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@medtrainer_queue:5672/%2F"
      RUSTICI_ENGINE_BASE_URL: http://rustici-engine:8080/RusticiEngine/api/v2
      RUSTICI_ENGINE_API_USERNAME: ${RUSTICI_ENGINE_API_USERNAME}
      RUSTICI_ENGINE_API_PASSWORD: ${RUSTICI_ENGINE_API_PASSWORD}
      RUSTICI_ENGINE_WEBHOOK_USERNAME: ${RUSTICI_ENGINE_API_ROLLUP_REGISTRATION_POST_BACK_USER}
      RUSTICI_ENGINE_WEBHOOK_PASSWORD: ${RUSTICI_ENGINE_API_ROLLUP_REGISTRATION_POST_BACK_PASSWORD}
    volumes:
      - ${COURSE_ASSIGNMENTS_CODE_PATH_HOST}:${CONTAINER_APP_PATH}
      - ./coverage:/opt/phpstorm-coverage
    tty: true
    networks: [backend]
    command: bin/console messenger:consume main -v --memory-limit=1GB --profile --no-reset
    depends_on:
      medtrainer_db:
        condition: service_healthy
      medtrainer_queue:
        condition: service_healthy

  course-assignments-api:
    build:
      target: development
      dockerfile: irene/course-assignments-api/Dockerfile
      args:
        APP_DIR: ${CONTAINER_APP_PATH}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_SESSION: PHPSTORM_COURSE_ASSIGNMENTS_BACKEND
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
      XDEBUG_CONFIG: "idekey=PHPSTORM_COURSE_ASSIGNMENTS_BACKEND"
      XDEBUG_MODE: debug
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@medtrainer_db/${MONOLITH_DATABASE}?serverVersion=8&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@medtrainer_queue:5672/%2F"
      RUSTICI_ENGINE_BASE_URL: http://rustici-engine:8080/RusticiEngine/api/v2
      RUSTICI_ENGINE_API_USERNAME: ${RUSTICI_ENGINE_API_USERNAME}
      RUSTICI_ENGINE_API_PASSWORD: ${RUSTICI_ENGINE_API_PASSWORD}
      RUSTICI_ENGINE_WEBHOOK_USERNAME: ${RUSTICI_ENGINE_API_ROLLUP_REGISTRATION_POST_BACK_USER}
      RUSTICI_ENGINE_WEBHOOK_PASSWORD: ${RUSTICI_ENGINE_API_ROLLUP_REGISTRATION_POST_BACK_PASSWORD}
    volumes:
      - ${COURSE_ASSIGNMENTS_CODE_PATH_HOST}:${CONTAINER_APP_PATH}
      - ./coverage:/opt/phpstorm-coverage
    tty: true
    networks: [backend]
    command: php-fpm --nodaemonize
    depends_on:
      medtrainer_queue:
        condition: service_healthy

  learning-notifications:
    build:
      target: development
      dockerfile: irene/learning-notifications/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - XDEBUG_SESSION=PHPSTORM_PAST_DUE_NOTIFICATION
      - PHP_IDE_CONFIG=serverName=learning-notifications
      - XDEBUG_CONFIG="idekey=PHPSTORM_PAST_DUE_NOTIFICATION"
      - XDEBUG_MODE=debug
    volumes:
      - ${PAST_DUE_NOTIFICATION_CODE_PATH_HOST}:${CONTAINER_APP_PATH}
      - ./coverage:/opt/phpstorm-coverage
    tty: true
    networks: [backend]
    command: bin/console messenger:consume scheduler_default main --memory-limit=128M -vv --profile
    depends_on:
      medtrainer_db:
        condition: service_healthy

  provider-profile:
    build:
      context: irene/reverse-proxy
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ${PROVIDER_PROFILE_CODE_PATH_HOST}:/var/www/provider-profile
      - ${PWD}/irene/reverse-proxy/sites/provider-profile.conf:/etc/nginx/sites-enabled/provider-profile.conf
    ports:
      - "83"
      - "8083:8083"
    networks: [backend]
    depends_on:
      - gateway
      - provider-profile-api

  provider-profile-api:
    image: medtrainer.azurecr.io/provider-profile-api-php:latest
    environment:
      APP_NAME: provider-profile-api
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ABC
      LMS_DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@medtrainer_db:3306/${MONOLITH_DATABASE}?serverVersion=8.0&charset=UTF8"
      LMS_DATABASE_URL_RO: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@medtrainer_db:3306/${MONOLITH_DATABASE}?serverVersion=8.0&charset=UTF8"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@medtrainer_queue:5672"
    command: php-fpm --nodaemonize
    networks: [backend]
