services:
selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
      - "4444:4444"
    expose:
      - "9515"
      - "4444"
    networks:
      - backend
    depends_on:
      - monolith
      - course-assignments-worker
      - spa
      - medtrainer_db

  symfony-performance-backend:
    build:
      target: development
      dockerfile: irene/php-fpm/Dockerfile
      args:
        APP_DIR: ${CONTAINER_APP_PATH}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - XDEBUG_SESSION=PHPSTORM_SYMFONY_PERFORMANCE
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
      - XDEBUG_CONFIG="idekey=PHPSTORM_PERFORMANCE"
      - XDEBUG_MODE=off
    volumes:
      - ${SYMFONY_PERFORMANCE_CODE_PATH_HOST}:${CONTAINER_APP_PATH}
      - ./coverage:/opt/phpstorm-coverage
    tty: true
    networks: [ backend ]
    command: php-fpm --nodaemonize
    depends_on:
      - medtrainer_db
      - medtrainer-queue

  symfony-performance:
    build:
      context: irene/reverse-proxy
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ${PWD}/irene/reverse-proxy/sites/symfony-performance.conf:/etc/nginx/sites-enabled/symfony-performance.conf
    ports:
      - "83"
    networks:
      - backend
    depends_on:
      - gateway
      - symfony-performance-backend